name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --group dev

    - name: Format check with black
      run: uv run black --check --diff src/ tests/

    - name: Type checking with mypy
      run: uv run mypy src/

    - name: Linting with flake8
      run: uv run flake8 src/ tests/

    - name: Run tests with pytest
      run: uv run python -m pytest tests/ -v --tb=short

    - name: Test coverage
      run: uv run python -m pytest tests/ --cov=src --cov-report=xml --cov-report=term

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --group dev

    - name: Security check with bandit
      run: uv run bandit -r src/
